// Define CATCH_CONFIG_MAIN to create main() function
#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"

// Main is automatically generated by Catch2
// All test files will be linked against this
